name: xNFT Bundle

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn bundle
        env:
          VITE_RPC_URL_MAINNET: ${{ secrets.VITE_RPC_URL_MAINNET }}
      - uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ${{ github.workspace }}/xnft-bundle.zip
